# Generated by Django 5.2.1 on 2025-05-19 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_total_earnings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='total_earnings',
        ),
    ]
