# Generated by Django 5.2.1 on 2025-05-20 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='user',
        ),
    ]
