# Generated by Django 5.2.1 on 2025-05-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_city_shipment_description_shipment_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='city',
            name='longitude',
        ),
        migrations.AddField(
            model_name='city',
            name='arabic_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
