# Generated by Django 5.2.1 on 2025-05-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_remove_city_latitude_remove_city_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='estimated_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
