# Generated by Django 5.2.1 on 2025-05-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_alter_shipment_estimated_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
    ]
