# Generated by Django 5.2.1 on 2025-05-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('total_earnings', models.FloatField(default=0)),
            ],
        ),
    ]
