# Generated by Django 5.2.1 on 2025-05-31 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('shipments', '0003_shipment_assigned_agent_shipment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_requests', to='agents.agent')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_requests', to='shipments.shipment')),
            ],
            options={
                'unique_together': {('agent', 'shipment')},
            },
        ),
    ]
