# Generated by Django 5.2.1 on 2025-05-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='available_shipments',
            field=models.ManyToManyField(blank=True, related_name='available_agents', to='shipments.shipment'),
        ),
    ]
